service: "reddit-favorites-newsletter"

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    AWS_SDK_LOAD_CONFIG: 0
    USERS_TABLE: Users-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}"

functions:
  createUser:
    handler: src/domains/users/infra/lambdas/createUser.handler
    events:
      - http:
          method: post
          path: users
          cors: true
  getUser:
    handler: src/domains/users/infra/lambdas/getUser.handler
    events:
      - http:
          method: get
          path: users/{id}
          cors: true
  listUsers:
    handler: src/domains/users/infra/lambdas/listUsers.handler
    events:
      - http:
          method: get
          path: users
          cors: true
  updateUser:
    handler: src/domains/users/infra/lambdas/updateUser.handler
    events:
      - http:
          method: put
          path: users/{id}
          cors: true
  deleteUser:
    handler: src/domains/users/infra/lambdas/deleteUser.handler
    events:
      - http:
          method: delete
          path: users/{id}
          cors: true
  getTop10Subreddit:
    handler: src/domains/reddit/infra/lambdas/getSubredditTop10.handler
    events:
      - http:
          method: get
          path: subreddit/{subreddit}
          cors: true
  newsletter:
    handler: src/domains/newsletters/infra/lambdas/sendNewsletters.handler
    events:
      - http:
          method: get
          path: newsletters
          cors: true
resources:
  Resources:
    PostsListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
